In [ ]:
!pip install cupy-cuda11x

In [ ]:
!nvcc --version

In [ ]:
!pip uninstall -y cupy cupy-cuda12x

In [ ]:
!apt-get update -y
!apt-get install -y cuda-toolkit-11-8

In [ ]:
!pip install cupy-cuda11x

In [ ]:
!nvcc --version

In [ ]:
!pip install -U cupy-cuda12x

In [ ]:
!nvcc --version


In [ ]:
!apt-get remove --purge '^cuda.*' -y
!apt-get remove --purge '^nvidia-.*' -y
!apt-get autoremove -y
!apt-get clean
!pip uninstall -y cupy cupy-cuda*


In [5]:
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
!dpkg -i cuda-keyring_1.0-1_all.deb
!apt-get update
!apt-get install -y cuda-toolkit-11-8


--2025-02-24 17:16:05--  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
Resolving developer.download.nvidia.com (developer.download.nvidia.com)... 23.210.244.218, 23.210.244.213, 23.210.244.205, ...
Connecting to developer.download.nvidia.com (developer.download.nvidia.com)|23.210.244.218|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4328 (4.2K) [application/x-deb]
Saving to: ‘cuda-keyring_1.0-1_all.deb’

cuda-keyring_1.0-1_ 100%[===================>]   4.23K  --.-KB/s    in 0s      

2025-02-24 17:16:06 (114 MB/s) - ‘cuda-keyring_1.0-1_all.deb’ saved [4328/4328]

dpkg: warning: downgrading cuda-keyring from 1.1-1 to 1.0-1
(Reading database ... 130262 files and directories currently installed.)
Preparing to unpack cuda-keyring_1.0-1_all.deb ...
Unpacking cuda-keyring (1.0-1) over (1.1-1) ...
Setting up cuda-keyring (1.0-1) ...
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://archive.ub

In [6]:
!pip install cupy-cuda11x


In [ ]:
import os
os._exit(0)


In [ ]:
import cupy as cp
print("CuPy version:", cp.__version__)
print("CUDA version:", cp.cuda.runtime.runtimeGetVersion())


In [ ]:
!pip install cupy-cuda12x --no-cache-dir


In [1]:
import cupy as cp
print("CuPy version:", cp.__version__)
print("CUDA version:", cp.cuda.runtime.runtimeGetVersion())


CuPy version: 13.3.0
CUDA version: 12060


In [9]:
!pip uninstall -y cupy cupy-cuda11x cupy-cuda12x


Found existing installation: cupy-cuda12x 13.3.0
Uninstalling cupy-cuda12x-13.3.0:
  Successfully uninstalled cupy-cuda12x-13.3.0


In [1]:
!pip install cupy-cuda12x==13.1.0


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 MB 5.8 MB/s eta 0:00:00
  Attempting uninstall: cupy-cuda12x
    Found existing installation: cupy-cuda12x 13.3.0
    Uninstalling cupy-cuda12x-13.3.0:
      Successfully uninstalled cupy-cuda12x-13.3.0


In [3]:
import cupy as cp
print(cp.cuda.is_available())
gpu_array = cp.array([1, 2, 3, 4, 5])
print(gpu_array)


True
[1 2 3 4 5]


In [4]:
a = cp.array([1, 2, 3])
b = cp.array([4, 5, 6])

print(a + b)
print(a * b)
print(cp.exp(a))

[5 7 9]
[ 4 10 18]
[ 2.71828183  7.3890561  20.08553692]


In [5]:
import numpy as np
cpu_array = np.array([1, 2, 3])
gpu_array = cp.array(cpu_array)
cpu_result = cp.asnumpy(gpu_array)

print("Numpy (CPU) Array:", cpu_array)
print("CuPy (GPU) Array:", gpu_array)
print("Converted:", cpu_result)

Numpy (CPU) Array: [1 2 3]
CuPy (GPU) Array: [1 2 3]
Converted: [1 2 3]


In [6]:
import cupy as cp
import numpy as np
import time

# Create a large NumPy array (100 million elements)
cpu_array = np.random.rand(100_000_000)

# Move to GPU
start_gpu = time.time()
gpu_array = cp.array(cpu_array)  # Transfer CPU -> GPU
end_gpu = time.time()

# Move back to CPU
start_cpu = time.time()
cpu_result = cp.asnumpy(gpu_array)  # Transfer GPU -> CPU
end_cpu = time.time()

print(f"CPU -> GPU Transfer Time: {end_gpu - start_gpu:.6f} sec")
print(f"GPU -> CPU Transfer Time: {end_cpu - start_cpu:.6f} sec")

# Measure repeated transfers
repeats = 10
start_repeat = time.time()
for _ in range(repeats):
    gpu_array = cp.array(cpu_array)  # CPU -> GPU
    cpu_result = cp.asnumpy(gpu_array)  # GPU -> CPU
end_repeat = time.time()

print(f"Average Transfer Time (CPU ↔ GPU, {repeats} times): {(end_repeat - start_repeat) / repeats:.6f} sec")


CPU -> GPU Transfer Time: 0.648601 sec
GPU -> CPU Transfer Time: 0.365107 sec
Average Transfer Time (CPU ↔ GPU, 10 times): 0.511249 sec
